package net.seniorsteps.senior.dal.entity;
// Generated Jan 8, 2020 9:50:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "branch", catalog = "senior_app"
)
public class Branch implements java.io.Serializable {

	private Integer id;
	private Area area;
	private Provider provider;
	private String nameAr;
	private String nameEn;
	private Date openAt;
	private Date closeAt;
	private String phone;
	private BigDecimal lat;
	private BigDecimal lng;
	private Set<DeliveryArea> deliveryAreas = new HashSet<DeliveryArea>(0);
	private Set<ProviderUser> providerUsers = new HashSet<ProviderUser>(0);
	private Set<Order> orders = new HashSet<Order>(0);

	public Branch() {
	}

	public Branch(Area area, Provider provider, String nameAr, String nameEn, Date openAt, Date closeAt) {
		this.area = area;
		this.provider = provider;
		this.nameAr = nameAr;
		this.nameEn = nameEn;
		this.openAt = openAt;
		this.closeAt = closeAt;
	}

	public Branch(Area area, Provider provider, String nameAr, String nameEn, Date openAt, Date closeAt, String phone, BigDecimal lat, BigDecimal lng, Set<DeliveryArea> deliveryAreas, Set<ProviderUser> providerUsers, Set<Order> orders) {
		this.area = area;
		this.provider = provider;
		this.nameAr = nameAr;
		this.nameEn = nameEn;
		this.openAt = openAt;
		this.closeAt = closeAt;
		this.phone = phone;
		this.lat = lat;
		this.lng = lng;
		this.deliveryAreas = deliveryAreas;
		this.providerUsers = providerUsers;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_id", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "provider_id", nullable = false)
	public Provider getProvider() {
		return this.provider;
	}

	public void setProvider(Provider provider) {
		this.provider = provider;
	}

	@Column(name = "name_ar", nullable = false)
	public String getNameAr() {
		return this.nameAr;
	}

	public void setNameAr(String nameAr) {
		this.nameAr = nameAr;
	}

	@Column(name = "name_en", nullable = false)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "open_at", nullable = false, length = 8)
	public Date getOpenAt() {
		return this.openAt;
	}

	public void setOpenAt(Date openAt) {
		this.openAt = openAt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "close_at", nullable = false, length = 8)
	public Date getCloseAt() {
		return this.closeAt;
	}

	public void setCloseAt(Date closeAt) {
		this.closeAt = closeAt;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "lat", precision = 10, scale = 8)
	public BigDecimal getLat() {
		return this.lat;
	}

	public void setLat(BigDecimal lat) {
		this.lat = lat;
	}

	@Column(name = "lng", precision = 11, scale = 8)
	public BigDecimal getLng() {
		return this.lng;
	}

	public void setLng(BigDecimal lng) {
		this.lng = lng;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<DeliveryArea> getDeliveryAreas() {
		return this.deliveryAreas;
	}

	public void setDeliveryAreas(Set<DeliveryArea> deliveryAreas) {
		this.deliveryAreas = deliveryAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<ProviderUser> getProviderUsers() {
		return this.providerUsers;
	}

	public void setProviderUsers(Set<ProviderUser> providerUsers) {
		this.providerUsers = providerUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
