package net.seniorsteps.senior.dal.entity;
// Generated Jan 8, 2020 9:50:27 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Consumer generated by hbm2java
 */
@Entity
@Table(name = "consumer", catalog = "senior_app", uniqueConstraints = {
	@UniqueConstraint(columnNames = "email"),
	@UniqueConstraint(columnNames = "phone")}
)
public class Consumer implements java.io.Serializable {

	private Integer id;
	private String phone;
	private String email;
	private String password;
	private String fullname;
	private String gender;
	private Set<ConsumerAddress> consumerAddresses = new HashSet<ConsumerAddress>(0);
	private Set<Order> orders = new HashSet<Order>(0);

	public Consumer() {
	}

	public Consumer(String phone, String email, String password, String fullname) {
		this.phone = phone;
		this.email = email;
		this.password = password;
		this.fullname = fullname;
	}

	public Consumer(String phone, String email, String password, String fullname, String gender, Set<ConsumerAddress> consumerAddresses, Set<Order> orders) {
		this.phone = phone;
		this.email = email;
		this.password = password;
		this.fullname = fullname;
		this.gender = gender;
		this.consumerAddresses = consumerAddresses;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "phone", unique = true, nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "fullname", nullable = false)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "gender", length = 20)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consumer")
	public Set<ConsumerAddress> getConsumerAddresses() {
		return this.consumerAddresses;
	}

	public void setConsumerAddresses(Set<ConsumerAddress> consumerAddresses) {
		this.consumerAddresses = consumerAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consumer")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
